# Matrix
To access matrix in python, we will need library ('numpy') in this case

To install numpy, type in the command below in your command prompt
1. python -m pip install numpy

In [1]:
import numpy as np

In [5]:
a = np.array([1,2,3])
b = [1,2,3]
print('The array of a is ', a , 'type of a is ', type(a))
print('The array of b is ', b , 'type of b is ', type(b))


The array of a is  [1 2 3] type of a is  <class 'numpy.ndarray'>
The array of b is  [1, 2, 3] type of b is  <class 'list'>


# Double Size Array
Given a table of x, y

| x | y | 
| 1 | 4 |
| 2 | 5 | 
| 3 | 6 | 

An array will be useful to convey the data in matrix form instead of general list

In [6]:
b = np.array([ [1,2,3], [4,5,6] ])
print(b)
print('Shape of matrix b is ', b.shape)

[[1 2 3]
 [4 5 6]]
Shape of matrix b is  (2, 3)


In [ ]:
# Ad

In [15]:
a = np.array([[1,2,3], [1,2,3]])
b = np.array([[1,5,3], [3,2,3]])
print(a-b)

[[ 0 -3  0]
 [-2  0  0]]


# Multiplication 
In order to multiply shape A = n x m , B = m x s

In [19]:
a = np.array([[1,2,3]]) # Shape 1 x 3 
b = np.array([ [3] , [2] ,[1] ])
print(a.shape)
print(b.shape)
np.dot(a,b)

(1, 3)
(3, 1)


array([[10]])